Repository LikeLion13-Team2/Team2-BackEnd, pull requests merged in 2025-07, with the labels that each got.

#9 ✨feat: 학습 세션 저장 (POST) API 구현
  src/main/java/com/poco/poco_backend/domain/studySession/controller/StudySessionController.java
  src/main/java/com/poco/poco_backend/domain/studySession/converter/StudySessionConverter.java
  src/main/java/com/poco/poco_backend/domain/studySession/dto/request/StudySessionRequestDTO.java
  src/main/java/com/poco/poco_backend/domain/studySession/dto/response/StudySessionResponseDTO.java
  src/main/java/com/poco/poco_backend/domain/studySession/entity/StudySession.java
  src/main/java/com/poco/poco_backend/domain/studySession/repostitory/StudySessionRepository.java
  src/main/java/com/poco/poco_backend/domain/studySession/service/command/StudySessionCommandService.java
  src/main/java/com/poco/poco_backend/domain/studySession/service/command/StudySessionCommandServiceImpl.java
Labels: ✨ feature

#13 🐛 fix: 환경변수 오타 재수정
  src/main/java/com/poco/poco_backend/global/security/jwt/JwtUtil.java
Labels: bug

#14 🐛 fix: ci/cd 파일에 환경변수 추가
  .github/workflows/cicd.yml
Labels: bug

#16 🐛 fix: ci/cd 파일에 큰따옴표 추가 (오타 수정)
  .github/workflows/cicd.yml
Labels: bug

#18 💚ci: cicd 환경변수 --env-file 방식으로 통합
  .github/workflows/cicd.yml
Labels: 🤍 ci/cd

#21 ♻️refactor: CORS 설정 수정
  src/main/java/com/poco/poco_backend/global/Config/CorsConfig.java
Labels: ♻️ refactor

#23 🐛 fix: ResponseEntity 제네릭 타입 명시
  src/main/java/com/poco/poco_backend/domain/member/service/GoogleLoginService.java
Labels: bug

#24 🐛 fix: MessageConverter 수동 주입 및 로그 출력 코드 추가
  src/main/java/com/poco/poco_backend/domain/member/service/GoogleLoginService.java
Labels: bug

#25 🐛 fix: RestTemplate의 생성 로직을 리스트 형식으로 변경하여 명시적으로 선후 관계 지정.
  src/main/java/com/poco/poco_backend/domain/member/service/GoogleLoginService.java
Labels: bug

#27 🐛 fix: 파일 변경 전으로 되돌림
  build.gradle
  src/main/java/com/poco/poco_backend/domain/member/service/GoogleLoginService.java
Labels: bug

#30 🐛 fix: 인가코드 URI 디코딩 코드 추가
  src/main/java/com/poco/poco_backend/domain/member/service/GoogleLoginService.java
Labels: bug

#34 🐛 fix: restTemplate 구성 방식 재변경
  src/main/java/com/poco/poco_backend/domain/member/service/GoogleLoginService.java
Labels: bug

#37 환경변수 관련 로그 추가
  src/main/java/com/poco/poco_backend/domain/member/service/GoogleLoginService.java
Labels: ✨ feature

#38 tokenResponse 관련 스택스레이싱
  src/main/java/com/poco/poco_backend/domain/member/service/GoogleLoginService.java
Labels: ✨ feature

#39 restTemplate 구성 방식 변경
  src/main/java/com/poco/poco_backend/domain/member/service/GoogleLoginService.java
Labels: ✨ feature

#42 127.0.0.1:5500 cors 허용
  src/main/java/com/poco/poco_backend/global/Config/CorsConfig.java
Labels: ✨ feature

#44 ♻️ refactor: 멤버-토큰 연관관계 설정 및 구글 로그인 요청 방식 변경
  src/main/java/com/poco/poco_backend/domain/member/controller/GoogleLoginController.java
  src/main/java/com/poco/poco_backend/domain/member/dto/request/CodeDTO.java
  src/main/java/com/poco/poco_backend/domain/member/entity/Member.java
  src/main/java/com/poco/poco_backend/domain/member/entity/Token.java
  src/main/java/com/poco/poco_backend/domain/member/service/GoogleLoginService.java
Labels: ♻️ refactor

#45 ✨ feat: 스터디 세션 API 구현
  src/main/java/com/poco/poco_backend/domain/member/exception/MemberErrorCode.java
  src/main/java/com/poco/poco_backend/domain/member/exception/MemberException.java
  src/main/java/com/poco/poco_backend/domain/studySession/controller/StudySessionController.java
  src/main/java/com/poco/poco_backend/domain/studySession/converter/StudySessionConverter.java
  src/main/java/com/poco/poco_backend/domain/studySession/dto/response/StudySessionResponseDTO.java
  src/main/java/com/poco/poco_backend/domain/studySession/exception/StudySessionErrorCode.java
  src/main/java/com/poco/poco_backend/domain/studySession/exception/StudySessionException.java
  src/main/java/com/poco/poco_backend/domain/studySession/repostitory/StudySessionRepository.java
  src/main/java/com/poco/poco_backend/domain/studySession/service/command/StudySessionCommandService.java
  src/main/java/com/poco/poco_backend/domain/studySession/service/command/StudySessionCommandServiceImpl.java
  src/main/java/com/poco/poco_backend/domain/studySession/service/query/StudySessionQueryService.java
  src/main/java/com/poco/poco_backend/domain/studySession/service/query/StudySessionQueryServiceImpl.java
  src/main/java/com/poco/poco_backend/global/code/BaseErrorCode.java
  src/main/java/com/poco/poco_backend/global/exception/CustomException.java
Labels: ✨ feature

#47 ♻️ refactor: cors 설정 수정 및 security config 메서드 파라미터 변경
  src/main/java/com/poco/poco_backend/global/Config/CorsConfig.java
  src/main/java/com/poco/poco_backend/global/Config/SecurityConfig.java
Labels: ♻️ refactor

#49 ♻️ refactor: jwt 인증 필터에서 CustomUserDetails 구성 방식 변경
  src/main/java/com/poco/poco_backend/global/Config/CorsConfig.java
  src/main/java/com/poco/poco_backend/global/Config/SecurityConfig.java
  src/main/java/com/poco/poco_backend/global/security/filter/JwtAuthorizationFilter.java
Labels: ♻️ refactor

#56 cors 패턴 명시
  src/main/java/com/poco/poco_backend/global/Config/CorsConfig.java
Labels: ✨ feature, ♻️ refactor

#57 cors 파일 수정
  src/main/java/com/poco/poco_backend/global/Config/CorsConfig.java
Labels: ♻️ refactor

#64 ✨ feat: 마이페이지- 회원 조회, 이름 변경, 목표 추가, 목표 삭제 구현
  src/main/java/com/poco/poco_backend/domain/member/controller/GoogleLoginController.java
  src/main/java/com/poco/poco_backend/domain/member/controller/MemberController.java
  src/main/java/com/poco/poco_backend/domain/member/dto/request/GoalDTO.java
  src/main/java/com/poco/poco_backend/domain/member/dto/request/MemberRequestDTO.java
  src/main/java/com/poco/poco_backend/domain/member/dto/response/MemberResponseDTO.java
  src/main/java/com/poco/poco_backend/domain/member/entity/Goal.java
  src/main/java/com/poco/poco_backend/domain/member/entity/Goals.java
  src/main/java/com/poco/poco_backend/domain/member/entity/Member.java
  src/main/java/com/poco/poco_backend/domain/member/entity/MemberGoal.java
  src/main/java/com/poco/poco_backend/domain/member/repository/GoalRepository.java
  src/main/java/com/poco/poco_backend/domain/member/repository/MemberRepository.java
  src/main/java/com/poco/poco_backend/domain/member/service/GoogleLoginService.java
  src/main/java/com/poco/poco_backend/domain/member/service/MemberService.java
  src/main/java/com/poco/poco_backend/global/Config/SwaggerConfig.java
  src/main/java/com/poco/poco_backend/global/security/filter/JwtAuthorizationFilter.java
Labels: ✨ feature

#66 컨트롤러 파라미터 수정 및 도커 로그 무시 처리
  src/main/java/com/poco/poco_backend/domain/member/controller/GoogleLoginController.java
  src/main/java/com/poco/poco_backend/domain/member/controller/MemberController.java
  src/main/java/com/poco/poco_backend/domain/member/dto/request/CodeDTO.java
  src/main/java/com/poco/poco_backend/domain/member/repository/MemberRepository.java
  src/main/java/com/poco/poco_backend/global/Config/SecurityConfig.java
  src/main/java/com/poco/poco_backend/global/security/auth/CustomUserDetails.java
  src/main/java/com/poco/poco_backend/global/security/filter/JwtAuthorizationFilter.java
Labels: bug

#67 멤버 생성 로직 수정
  src/main/java/com/poco/poco_backend/domain/member/service/GoogleLoginService.java
Labels: bug

#70 목표 수정 방식 변경
  src/main/java/com/poco/poco_backend/domain/member/controller/MemberController.java
  src/main/java/com/poco/poco_backend/domain/member/dto/request/GoalDTO.java
  src/main/java/com/poco/poco_backend/domain/member/entity/Member.java
  src/main/java/com/poco/poco_backend/domain/member/service/MemberService.java
Labels: ✨ feature

#75 ♻️ refactor: 회원 삭제 로직 리팩터링
  src/main/java/com/poco/poco_backend/domain/member/repository/GoalRepository.java
  src/main/java/com/poco/poco_backend/domain/member/repository/MemberGoalRepository.java
  src/main/java/com/poco/poco_backend/domain/member/service/MemberService.java
  src/main/java/com/poco/poco_backend/domain/report/repository/ReportSessionRepository.java
  src/main/java/com/poco/poco_backend/domain/studySession/repostitory/StudySessionRepository.java
Labels: ✨ feature

#77 ♻️ refactor: 세션 목록 조회 시 세션 아이디 값 추가
  src/main/java/com/poco/poco_backend/domain/studySession/converter/StudySessionConverter.java
  src/main/java/com/poco/poco_backend/domain/studySession/dto/response/StudySessionResponseDTO.java
Labels: ♻️ refactor
